{"data":{"partNo":{"catCode":null,"clsCode":"5","clsCodeDesc":"小小电容","createTime":"2010-03-20 00:00:00","dynamicFields":{},"end":9999999,"order":null,"partNo":"GLE0001","pnDesc":"小小电容","price":0.2000,"sort":null,"start":0,"taxPrice":0.3000}},"success":true}