{"data":{"list":[{"text":"电容","leaf":false,"children":[{"text":"大电容","leaf":true,"children":[],"id":3},{"text":"小电容","leaf":false,"children":[{"text":"小小电容","leaf":true,"children":[],"id":5}],"id":4}],"id":1},{"text":"电阻","leaf":true,"children":[],"id":2}]},"success":true} 