{
    "data": {
        "list": [
            {
                "activeState": "ACTIVE",
                "bizKey": "11111;ddaa11",
                "commCode": "11111",
                "companyBranch": "1",
                "companyBranchDesc": "格莱尔",
                "conFax": "1",
                "conName": "1",
                "conTel": "1",
                "createTime": null,
                "dynamicFields": {},
                "end": 9999999,
                "fristCreateTime": "2010-03-02 22:52:28",
                "isShowPrice": "0",
                "isShowPriceDesc": "是",
                "logBizKey": "11111;ddaa11",
                "oderTime": "2010-03-02 00:00:00",
                "order": null,
                "orderDetailList": null,
                "period": "201003",
                "poNo": "ddaa11",
                "poNoType": "0",
                "receiveAddress": "1111111",
                "receiveName": "11",
                "receiveZip": "11111",
                "sales": "user1",
                "salesId": "1",
                "settlementType": "1",
                "settlementTypeDesc": "账期结算",
                "shortName": "11111",
                "sort": null,
                "staffId": "1",
                "staffName": "user1",
                "start": 0,
                "state": "33",
                "stateDesc": "未定义(01)",
                "vendorCode": "11111",
                "waitTaskBizKey": "11111订单号为ddaa11"
            }
        ],
        "count": 1,
        "jq": [
            ""
        ]
    },
    "success": true
}