{
    "data": {
        "list": [
            {
                "list": [
                    {
                        "title": "市场部业务员",
                        "name": "r_1000"
                    },
                    {
                        "list": [
                            {
                                "value": "a_1",
                                "title": "提交"
                            },
                            {
                                "value": "a_2",
                                "title": "保存"
                            }
                        ],
                        "title": "客户信息录入",
                        "name": "r_1100"
                    },
                    {
                        "list": [
                            {
                                "value": "a_1",
                                "title": "查询"
                            }
                        ],
                        "title": "客户信息查询",
                        "name": "r_1200"
                    },
                    {
                        "title": "采购部采购员",
                        "name": "r_2000"
                    },
                    {
                        "list": [
                            {
                                "value": "a_1",
                                "title": "提交"
                            },
                            {
                                "value": "a_2",
                                "title": "保存"
                            }
                        ],
                        "title": "供应商信息录入",
                        "name": "r_2100"
                    }
                ],
                "title": "test",
                "title22": "哈哈哈哈"
            }
        ]
    },
    "success": true
}