# MySQL-Front 5.0  (Build 1.133)

/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE */;
/*!40101 SET SQL_MODE='' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES */;
/*!40103 SET SQL_NOTES='ON' */;


# Host: 192.168.1.29    Database: testdb
# ------------------------------------------------------
# Server version 5.0.81-community

#
# Dumping data for table t_system_config
#
delete from `t_system_config`;
commit;
INSERT INTO `t_system_config` (`CONFIG_NAME`,`CONFIG_VALUE`,`VALUE_TYPE`,`VALUE_RANGE`,`CONFIG_DESC`,`VISIBLE_FLAG`,`CONFIG_REGION`,`SUB_SYSTEM`,`LAST_UPDATE`) VALUES ('ADJUST_REMINDER_DAY','2',0,NULL,'调货管理提醒时长','Y',NULL,NULL,NULL);
INSERT INTO `t_system_config` (`CONFIG_NAME`,`CONFIG_VALUE`,`VALUE_TYPE`,`VALUE_RANGE`,`CONFIG_DESC`,`VISIBLE_FLAG`,`CONFIG_REGION`,`SUB_SYSTEM`,`LAST_UPDATE`) VALUES ('CUSTOMERINFO_REMINDER_DAY','2',0,NULL,'客户信息审批通过提醒时长','Y',NULL,NULL,NULL);
INSERT INTO `t_system_config` (`CONFIG_NAME`,`CONFIG_VALUE`,`VALUE_TYPE`,`VALUE_RANGE`,`CONFIG_DESC`,`VISIBLE_FLAG`,`CONFIG_REGION`,`SUB_SYSTEM`,`LAST_UPDATE`) VALUES ('CUST_ORDER_REMINDER_DAY','3',0,NULL,'客户订单提醒时长','Y',NULL,NULL,NULL);
INSERT INTO `t_system_config` (`CONFIG_NAME`,`CONFIG_VALUE`,`VALUE_TYPE`,`VALUE_RANGE`,`CONFIG_DESC`,`VISIBLE_FLAG`,`CONFIG_REGION`,`SUB_SYSTEM`,`LAST_UPDATE`) VALUES ('CUST_PARTNO_REMINDER_DAY','2',0,NULL,'客户物料关系提醒时长','Y',NULL,NULL,NULL);
INSERT INTO `t_system_config` (`CONFIG_NAME`,`CONFIG_VALUE`,`VALUE_TYPE`,`VALUE_RANGE`,`CONFIG_DESC`,`VISIBLE_FLAG`,`CONFIG_REGION`,`SUB_SYSTEM`,`LAST_UPDATE`) VALUES ('CUST_REMINDER_DAY','5',0,NULL,'客户对账日/结算日提醒时长(天)','Y',NULL,NULL,NULL);
INSERT INTO `t_system_config` (`CONFIG_NAME`,`CONFIG_VALUE`,`VALUE_TYPE`,`VALUE_RANGE`,`CONFIG_DESC`,`VISIBLE_FLAG`,`CONFIG_REGION`,`SUB_SYSTEM`,`LAST_UPDATE`) VALUES ('PREPAID_REMINDER_DAY','5',0,NULL,'客户催款提醒时长(天)','Y',NULL,NULL,NULL);
INSERT INTO `t_system_config` (`CONFIG_NAME`,`CONFIG_VALUE`,`VALUE_TYPE`,`VALUE_RANGE`,`CONFIG_DESC`,`VISIBLE_FLAG`,`CONFIG_REGION`,`SUB_SYSTEM`,`LAST_UPDATE`) VALUES ('VENDORINFO_REMINDER_DAY','2',0,NULL,'供应商信息审批通过提醒时长','Y',NULL,NULL,NULL);
INSERT INTO `t_system_config` (`CONFIG_NAME`,`CONFIG_VALUE`,`VALUE_TYPE`,`VALUE_RANGE`,`CONFIG_DESC`,`VISIBLE_FLAG`,`CONFIG_REGION`,`SUB_SYSTEM`,`LAST_UPDATE`) VALUES ('VENDOR_PARTNO_REMINDER_DAY','2',0,NULL,'供应商物料关系提醒时长','Y',NULL,NULL,NULL);
INSERT INTO `t_system_config` (`CONFIG_NAME`,`CONFIG_VALUE`,`VALUE_TYPE`,`VALUE_RANGE`,`CONFIG_DESC`,`VISIBLE_FLAG`,`CONFIG_REGION`,`SUB_SYSTEM`,`LAST_UPDATE`) VALUES ('VENDOR_REMINDER_DAY','5',0,NULL,'供应商对账日/结算日提醒时长(天)','Y',NULL,NULL,NULL);
commit;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
