{"data":{"list":[{"activeState":"ACTIVE","amount":1000,"commCode":"GV0001","commDesc":null,"cpartNo":"GLE0003","cprice":0.7000,"cpriceTax":0.6000,"custCcode":"GC0001","deliveryAmount":0,"dynamicFields":{},"end":9999999,"isTax":"1","logKey":"GV0001;GVK00013","money":null,"operSeqId":3,"order":null,"orgDeliveryDate":"2010-03-20 00:00:00","partNo":"GLE0003","period":"201003","pnDesc":"YANGZJTEST","poNo":"GVK0001","poNoType":"0","rltOrderPoNo":null,"rltRecPoNo":null,"settlementType":"1","settlementTypeDesc":"结算方式","shortName":"AAA","sort":null,"specDesc":null,"staffId":"1","staffName":"YANGZJ","start":0,"state":"02","taxRate":0.17,"verDeliveryDate":"2010-03-20 00:00:00"}],"count":1},"success":true} 
