# MySQL-Front 5.0  (Build 1.133)

/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE */;
/*!40101 SET SQL_MODE='' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES */;
/*!40103 SET SQL_NOTES='ON' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS */;
/*!40014 SET FOREIGN_KEY_CHECKS=0 */;


# Host: localhost    Database: testdb
# ------------------------------------------------------
# Server version 5.1.36-community

#
# Dumping data for table t_system_config
#
LOCK TABLES `t_system_config` WRITE;
/*!40000 ALTER TABLE `t_system_config` DISABLE KEYS */;

INSERT INTO `t_system_config` (`CONFIG_NAME`,`CONFIG_VALUE`,`VALUE_TYPE`,`VALUE_RANGE`,`CONFIG_DESC`,`VISIBLE_FLAG`,`CONFIG_REGION`,`SUB_SYSTEM`,`LAST_UPDATE`) VALUES ('CUST_REMINDER_DAY','5',0,NULL,'客户对账日/结算日提醒时长(天)','Y',NULL,NULL,NULL);
INSERT INTO `t_system_config` (`CONFIG_NAME`,`CONFIG_VALUE`,`VALUE_TYPE`,`VALUE_RANGE`,`CONFIG_DESC`,`VISIBLE_FLAG`,`CONFIG_REGION`,`SUB_SYSTEM`,`LAST_UPDATE`) VALUES ('PREPAID_REMINDER_DAY','5',0,NULL,'客户催款提醒时长(天)','Y',NULL,NULL,NULL);
INSERT INTO `t_system_config` (`CONFIG_NAME`,`CONFIG_VALUE`,`VALUE_TYPE`,`VALUE_RANGE`,`CONFIG_DESC`,`VISIBLE_FLAG`,`CONFIG_REGION`,`SUB_SYSTEM`,`LAST_UPDATE`) VALUES ('VENDOR_REMINDER_DAY','5',0,NULL,'供应商对账日/结算日提醒时长(天)','Y',NULL,NULL,NULL);
/*!40000 ALTER TABLE `t_system_config` ENABLE KEYS */;
UNLOCK TABLES;

/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
