


INSERT INTO `t_sys_sequence` (`SEQ_TYPE`,`SEQ_KEY`,`SEQ_VALUE`,`SEQ_LENGTH`,`SEQ_PREFIX`,`SEQ_MIDDLE`) VALUES ('GC_CODE','NNNN',0,4,'GC','0000');
INSERT INTO `t_sys_sequence` (`SEQ_TYPE`,`SEQ_KEY`,`SEQ_VALUE`,`SEQ_LENGTH`,`SEQ_PREFIX`,`SEQ_MIDDLE`) VALUES ('GV_CODE','NNNN',0,4,'GV','0000');
COMMIT;
