{
    "data": {
        "list": [
            {
                
                "key": "1",
                "value": "系统类"
            },
            {
                "key": "8019011",
                "value": "应用软件类"
            },
            {
                "key": "8019012",
                "value": "其它"
            }
        ]
    },
    "success": true
}