# MySQL-Front 5.0  (Build 1.133)

/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE */;
/*!40101 SET SQL_MODE='' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES */;
/*!40103 SET SQL_NOTES='ON' */;


# Host: localhost    Database: testdb
# ------------------------------------------------------
# Server version 5.1.36-community

#
# Dumping data for table action
#


INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (1100,'1','customerInfo/customerInfo!save.action','commit','提交');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (1100,'2','customerInfo/customerInfo!saveTemp.action','savetemp','保存');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (1200,'1','customerInfo/customerInfo!list.action','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (1200,'2','','update','修改');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (1200,'3','','delete','废除');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (1300,'1','','save','保存');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (1400,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (1400,'2','','update','修改');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (1400,'3','','delete','废除');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (1500,'1','','commit','提交');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (1500,'2','','savetemp','保存');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (1600,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (1600,'2','','delete','废除');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (1600,'3','','update','修改');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (1700,'1','','save','保存');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (1800,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (2100,'1','vendorInfo/vendorInfo!save.action','commit','提交');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (2100,'2','vendorInfo/vendorInfo!saveTemp.action','savetemp','保存');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (2200,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (2200,'2','','update','修改');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (2200,'3','','delete','废除');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (2300,'1','','save','保存');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (2400,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (2400,'2','','update','修改');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (2400,'3','','delete','废除');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (2500,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (2600,'1','','commit','提交');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (2600,'2','','savetemp','保存');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (2700,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (2700,'2','','update','修改');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (2700,'3','','delete','废除');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (3100,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (3100,'2','','audit','审批');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (3200,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (3200,'2','','audit','审批');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (3300,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (3300,'2','','audit','审批');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (3400,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (3400,'2','','audit','审批');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (3500,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (3500,'2','','audit','审批');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (3600,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (3600,'2','','audit','审批');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (4100,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (4100,'2','','audit','审批');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (4200,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (4200,'2','','audit','审批');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (4300,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (4300,'2','','audit','审批');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (4400,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (4500,'2','','audit','审批');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (5100,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (5200,'1','','save','保存');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (5200,'2','','commit','提交');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (5300,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (5300,'2','','update','修改');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (5300,'3','','delete','删除');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (5400,'1','','save','保存');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (5400,'2','','commit','提交');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (5500,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (5500,'2','','update','修改');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (5500,'3','','delete','删除');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (6100,'1','','commit','提交');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (6200,'1','','commit','提交');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (6300,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (6300,'2','','audit','审批');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (6400,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (6400,'2','','audit','审批');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (6500,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (6500,'2','','audit','结算');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (6600,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (6600,'2','','audit','对账');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (6700,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (6700,'2','','audit','对账');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (6800,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (6800,'2','','audit','更新状态');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (6900,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (6900,'2','','audit','更新状态');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (6910,'1','','add','新增');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (6910,'2','','update','修改');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (6910,'3','','delete','删除');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (6910,'4','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (6920,'1','','add','新增');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (6920,'2','','update','修改');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (6920,'3','','delete','删除');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (6920,'4','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (7100,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (7100,'2','','audit','审批');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (9100,'1','auth/user!list.action','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (9100,'2','auth/user!del.action','delete','删除');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (9100,'3','','add','新增');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (9101,'1','auth/user!save.action','save','保存');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (9102,'1','auth/user!save.action','save','保存');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (9200,'1','auth/role!list.action','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (9200,'2','','delete','删除');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (9200,'3','','add','新增');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (9201,'1','','save','保存');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (9202,'1','','save','保存');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (9300,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (9300,'2','','delete','删除');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (9300,'3','','add','新增');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (9301,'1','','save','保存');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (9302,'1','','save','保存');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (9400,'1','','save','保存');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (10100,'1','','save','保存');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (10200,'1','','query','查询');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (10200,'2','','update','修改');
INSERT INTO `action` (`ACTIONS_ID`,`ACTION_ID`,`ACTION_NAME`,`BUTTON_ID`,`DESCRIPTION`) VALUES (10200,'3','','delete','删除');

/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
