{"data":{"encodeDict":[{"dynamicFields":{},"encodeDesc":"子系统类型","encodeKey":"1","encodeType":"110_SUBSYSTEM","encodeValue":"系统类","end":9999999,"isValid":"Y","order":null,"sort":null,"sortId":"54","start":1},{"dynamicFields":{},"encodeDesc":"子系统类型","encodeKey":"8019011","encodeType":"110_SUBSYSTEM","encodeValue":"应用软件类","end":9999999,"isValid":"Y","order":null,"sort":null,"sortId":"54","start":1},{"dynamicFields":{},"encodeDesc":"子系统类型","encodeKey":"8019012","encodeType":"110_SUBSYSTEM","encodeValue":"其它","end":9999999,"isValid":"Y","order":null,"sort":null,"sortId":"54","start":1}]},"success":true}