{
    "data": {
        "vendorPartNoInfo": {
            "catCode": null,
            "clsName": "5",
            "commCode": "GV0001",
            "createDate": "2010-03-20 00:00:00",
            "custPartNo": "GV_PART_NO_0001",
            "dynamicFields": {},
            "end": 9999999,
            "isPriceChange": "0",
            "logBizKey": "GLE0001;GV_PART_NO_0001;GV0001",
            "logContent": "公司物料编码:GLE0001  供应商物料编码:GV_PART_NO_0001  供应商编码:GV0001  单价:0.5  含税单价:0.17  ",
            "minAmount": 2,
            "minPackage": 0,
            "order": null,
            "partNo": "GLE0001",
            "pnDesc": "小小电容",
            "price": 0.5,
            "priceTax": 0.17,
            "sampleCode": "ABCD",
            "seqId": 3,
            "sort": null,
            "staffId": "1",
            "staffName": "user1",
            "start": 0,
            "state": "2",
            "stateDesc": "待审批数据",
            "waitTaskBizKey": "GLE0001;GV_PART_NO_0001;GV0001"
        },
        "vendorInfo": {
            "accountPreiod": null,
            "address": "深圳",
            "allName": "宗军",
            "baseSeqId": 5,
            "commCode": "GV0001",
            "commDesc": "abcdeg",
            "commScale": "20-50",
            "commType": "台资",
            "companyBranch": "1",
            "companyBranchDesc": "格莱尔",
            "contactFee": 0.01,
            "createTime": null,
            "creditDesc": "一般",
            "creditRate": "3",
            "currency": "1",
            "currencyDesc": "人民币",
            "dynamicFields": {},
            "enAddress": "shenzhen",
            "enName": "gv0001",
            "enShortName": "sz",
            "end": 9999999,
            "importantCode": "1",
            "importantDesc": "一般",
            "isShowPrice": "1",
            "isShowPriceDesc": "否",
            "listBankInfo": null,
            "listContactInfo": null,
            "logKey": "GV0001",
            "order": null,
            "prePaidInfo": null,
            "representative": "YZJ",
            "settlementDesc": "账期结算",
            "settlementType": "1",
            "shortName": "G测试",
            "sort": null,
            "staffId": "1",
            "staffName": "yzj",
            "start": 0,
            "state": "0",
            "stateDesc": "正式数据",
            "taxCode": "1234",
            "taxRate": 0.17,
            "vendorCode": null,
            "waitTaskKey": "GV0001",
            "webSite": " www.sz.com"
        }
    },
    "success": true
}