{
    "data": {
        "custPartNoInfo": {
            "catCode": null,
            "clsName": "5",
            "commCode": "GC0001",
            "createDate": "2010-03-28 16:59:49",
            "custPartNo": "KH0001",
            "dynamicFields": {},
            "end": 9999999,
            "isPriceChange": "0",
            "logBizKey": "GLE0001;KH0001;GC0001",
            "logContent": "公司物料编码:GLE0001  客户物料编码:KH0001  客户编码:GC0001  单价:10.0  含税单价:0.17  ",
            "minAmount": 100,
            "order": null,
            "partNo": "GLE0001",
            "pnDesc": "小小电容",
            "price": 10,
            "priceTax": 0.17,
            "sampleCode": "ABCD",
            "seqId": 5,
            "sort": null,
            "staffId": "1",
            "staffName": "user1",
            "start": 0,
            "state": "0",
            "stateDesc": "正式数据",
            "vendorCode": "GV0002",
            "waitTaskBizKey": "GLE0001;KH0001;GC0001"
        },
        "custInfo": {
            "accountPreiod": null,
            "address": "深圳",
            "allName": "测试YANGZJ1",
            "assStaffId": "1",
            "assStaffName": "yzj",
            "baseSeqId": 23,
            "commCode": "GC0001",
            "commDesc": "是个好客户",
            "commScale": "20-200",
            "commType": "美资",
            "companyBranch": "1",
            "companyBranchDesc": "格莱尔",
            "contactFee": 0.01,
            "createTime": "2010-03-27 11:56:32",
            "creditDesc": "一般",
            "creditRate": "3",
            "currency": "2",
            "currencyDesc": "美元",
            "dynamicFields": {},
            "enAddress": "YANGZJ",
            "enName": "YANGZJ",
            "enShortName": "YANGZJ",
            "end": 9999999,
            "importantCode": "2",
            "importantDesc": "重要",
            "isShowPrice": "0",
            "isShowPriceDesc": "是",
            "listBankInfo": null,
            "listContactInfo": null,
            "order": null,
            "partNoInfoList": null,
            "prePaidInfo": null,
            "representative": "YANGZJ",
            "settlementDesc": "预付X%,剩余货到付款",
            "settlementType": "2",
            "shortName": "测试",
            "sort": null,
            "staffId": "1",
            "staffName": "yzj",
            "start": 0,
            "state": "0",
            "stateDesc": "正式数据",
            "taxCode": "123456",
            "taxRate": 0.17,
            "vendorCode": "GV0002",
            "webSite": " www.yangzj.com"
        }
    },
    "success": true
}