{"data":{"custPartNoInfo":{"catCode":null,"clsName":"5","commCode":"GC0001","createDate":"2010-03-28 16:59:49","custPartNo":"KH0001","dynamicFields":{},"end":9999999,"isPriceChange":"0","logBizKey":"GLE0001;KH0001;GC0001","logContent":"公司物料编码:GLE0001  客户物料编码:KH0001  客户编码:GC0001  单价:10.0  含税单价:0.17  ","minAmount":100,"order":null,"partNo":"GLE0001","pnDesc":"小小电容","price":10.0000,"priceTax":0.1700,"sampleCode":"ABCD","seqId":5,"sort":null,"staffId":"1","staffName":"user1","start":0,"state":"0","stateDesc":"正式数据","vendorCode":"GV0002","waitTaskBizKey":"GLE0001;KH0001;GC0001"}},"success":true} 