{
    "data": {
        "list": [
            {
                "accountPreiod": null,
                "address": "ffsf",
                "allName": "adsfasd",
                "assStaffId": "1",
                "assStaffName": "123",
                "baseSeqId": 1,
                "commCode": "1111",
                "commDesc": "",
                "commScale": "1",
                "commType": "1",
                "companyBranch": "格莱尔",
                "contactFee": null,
                "creditDesc": "一般",
                "creditRate": "3",
                "currency": "1",
                "currencyDesc": "人民币",
                "dynamicFields": {},
                "enAddress": "",
                "enName": "",
                "enShortName": "",
                "end": 9999999,
                "importantCode": "1",
                "importantDesc": "一般",
                "isShowPrice": "0",
                "listBankInfo": null,
                "listContactInfo": null,
                "order": null,
                "partNoInfoList": null,
                "prePaidInfo": null,
                "representative": "",
                "settlementDesc": "账期结算",
                "settlementType": "1",
                "shortName": "aasdf",
                "sort": null,
                "staffId": "1",
                "staffName": "user1",
                "start": 0,
                "state": "1",
                "taxCode": "",
                "taxRate": null,
                "vendorCode": "123",
                "webSite": ""
            },
            {
                "accountPreiod": null,
                "address": "adsf",
                "allName": "asdf",
                "assStaffId": "1",
                "assStaffName": "123",
                "baseSeqId": 2,
                "commCode": "2222",
                "commDesc": "",
                "commScale": "",
                "commType": "1",
                "companyBranch": "格莱尔",
                "contactFee": null,
                "creditDesc": "良",
                "creditRate": "2",
                "currency": null,
                "currencyDesc": null,
                "dynamicFields": {},
                "enAddress": "",
                "enName": "",
                "enShortName": "",
                "end": 9999999,
                "importantCode": "2",
                "importantDesc": "重要",
                "isShowPrice": "1",
                "listBankInfo": null,
                "listContactInfo": null,
                "order": null,
                "partNoInfoList": null,
                "prePaidInfo": null,
                "representative": "",
                "settlementDesc": "预付X%,剩余货到付款",
                "settlementType": "2",
                "shortName": "sadf",
                "sort": null,
                "staffId": "1",
                "staffName": "user1",
                "start": 0,
                "state": "2",
                "taxCode": "",
                "taxRate": null,
                "vendorCode": "321",
                "webSite": ""
            }
        ],
        "count": 2
    },
    "success": true
}